### PR TITLE
Attempt to improve homepage title (linear gradient)

### LINKED ISSUE #50: Make Homepage "Coding a better world together" bolder with more contrast

### PR DESCRIPTION
**Pull request by 7riumph**
Screenshot from 2022-09-04 13-03-09

Screenshot from 2022-09-04 13-03-40

### CODE REVIEW

**Review by tylerlam1 — COMMENTED** [review]
@harsohailB @topanb11 I'm alright with this change and think it adds a nice touch - however it does appear the contrast with the underlying image is slightly worse now. What do both of you think?

**Comment by 7riumph** [comment]
Oh, I can boost the contrast a bit (any higher and it looks weird on mobile tho); how does this look? 

More contrast version: https://code-the-change-yyc-site-n99o4jxjv-code-the-change-yyc.vercel.app/ 
Old version: https://code-the-change-yyc-site-hiyqtd5qi-code-the-change-yyc.vercel.app/

**Review by tylerlam1 — COMMENTED** [review]
This looks good to me. Just wanted to make sure @topanb11 and @harsohailB are good with this change before approving it.

Those errors you see in the browser console look unrelated to your PR. Can you make another issue to fix those console errors?

**Comment by harsohailB** [comment]
> This looks good to me. Just wanted to make sure @topanb11 and @harsohailB are good with this change before approving it.
> 
> Those errors you see in the browser console look unrelated to your PR. Can you make another issue to fix those console errors?

Let's have design take a look at this? I'm totally fine with this but my knowledge about design in not the best lol

@7riumph if you can post some screenshots in the `brand-website-redesign` and tag Sophia and Natalia

**Comment by harsohailB** [comment]
@tylerlam1 @7riumph Attempted to fix this in #65 with opacity. Added you as reviewers. I think that solution works well!

**Pull request closed without merging**
