### PR TITLE
New map topojson uploaded and used.  Map component updated to use new…

### PR DESCRIPTION
**Pull request by burtonjong**
... data. The original problem with the map was that the user who provided the topojson deleted his repo, thus I replaced it with another from https://cartographyvectors.com/map/793-combined-us-canada-with-states-provinces and used https://mapshaper.org/ to change the GeoJson to Topojson.

Look on desktop:
image

Look on mobile: 
image

There is also the fact that when clicked, a square appears on the state/province:
image

Maybe this was a function that was used before...? I am not sure. Let me know what I should change (especially on mobile, we could use a media query to increase the size of text cause it looks small)

### CODE REVIEW

**Comment by justin-phxm** [comment]
On mobile, the map looks very small, maybe you can zoom in a little bit? Otherwise, looks pretty good!

**Review by topanb11 — COMMENTED** [review]
map looks good on desktop and mobile! I also agree, it would be good to increase the text size on mobile

with the clicking on the map, maybe it's used for if you wanna focus on a certain province/state? I don't think you need to do anything extra with it though

**Comment by burtonjong** [comment]
image
Updated mobile view. Desktop text size stayed the same

**Review by topanb11 — APPROVED** [review]
thanks Burton! LGTM

**Pull request merged**
